openapi: 3.0.0
x-stoplight:
  id: xvjyl3m0cino3
info:
  title: SSW HRMS API
  version: 1.1.0
  description: SSW HRMS API
  contact:
    name: PIC
    email: Ysiki.Shokurin@gmail.com
  license:
    name: MIT
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples: {}
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples: {}
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples: {}
        description: Patch user properties to update.
  /users:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    id: '123456789012345678'
                    name: string
                    joined_at: '2019-08-24'
                    left_at: '2019-08-24'
                    comment: string
                    departments:
                      - 0
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      description: Create a new user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples: {}
        description: ''
    parameters: []
    get:
      summary: ''
      operationId: get-users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              examples: {}
  /organizations:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
      operationId: get-organizations
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      properties:
        id:
          type: string
          description: Unique identifier for the given user.
          minLength: 18
          maxLength: 18
        name:
          type: string
        joined_at:
          type: string
          format: date
        left_at:
          type: string
          format: date
        comment:
          type: string
        departments:
          type: array
          items:
            type: integer
    Organization:
      title: Organization
      x-stoplight:
        id: m0hb384vjlx0h
      type: object
      properties:
        name:
          type: string
        boss_id:
          type: string
        member_ids:
          type: array
          items:
            type: string
        subsets:
          type: array
          items:
            $ref: '#/components/schemas/Organization'
  securitySchemes: {}
