openapi: 3.0.0
x-stoplight:
  id: xvjyl3m0cino3
info:
  title: SSW HRMS API
  version: 1.1.0
  description: SSW HRMS API
  contact:
    name: PIC
    email: Ysiki.Shokurin@gmail.com
  license:
    name: MIT
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples: {}
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples: {}
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples: {}
        description: Patch user properties to update.
  /users:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    id: '123456789012345678'
                    name: string
                    joined_at: '2019-08-24'
                    left_at: '2019-08-24'
                    comment: string
                    departments:
                      - 0
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      description: Create a new user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples: {}
        description: ''
    parameters: []
    get:
      summary: ''
      operationId: get-users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              examples: {}
  /organizations:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AA'
      operationId: get-organizations
    post:
      summary: ''
      operationId: post-organizations
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/OrganizationBase'
                - type: object
                  properties:
                    super_org_id:
                      type: string
                    boss_role_id:
                      type: string
                    member_role_id:
                      type: string
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      properties:
        id:
          type: string
          description: Unique identifier for the given user.
          minLength: 18
          maxLength: 18
        name:
          type: string
        joined_at:
          type: string
          format: date
        left_at:
          type: string
          format: date
        comment:
          type: string
        departments:
          type: array
          items:
            type: integer
    OrganizationBase:
      title: OrganizationBase
      x-stoplight:
        id: m0hb384vjlx0h
      type: object
      properties:
        name:
          type: string
    Organization:
      title: Organization
      x-stoplight:
        id: 30j3sjyvm2dl4
      allOf:
        - $ref: '#/components/schemas/OrganizationBase'
        - type: object
          properties:
            id:
              type: string
            boss_role:
              $ref: '#/components/schemas/Role'
            member_role:
              $ref: '#/components/schemas/Role'
            subsets:
              type: array
              items:
                $ref: '#/components/schemas/Organization'
      description: ''
    Role:
      title: Role
      x-stoplight:
        id: kuh7zkvjxvx84
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        user_ids:
          type: array
          items:
            type: string
    AA:
      title: AA
      x-stoplight:
        id: bgm7de3vw16gm
      type: object
      properties:
        boss:
          type: object
          properties:
            user_id:
              type: string
            role_name:
              type: string
        member:
          type: object
          properties:
            user_ids:
              type: array
              items:
                type: string
            role_name:
              type: string
        subsets:
          type: array
          items:
            $ref: '#/components/schemas/AA'
  securitySchemes: {}
